// src/components/layout/NavBar/NavDropdown.vue
<template>
  <div :class="s.dropdown">
    <div :class="s.grid">
      <a v-for="item in items" :key="item.title" :href="item.href" :class="s.item">
        <span :class="s.icon">{{ item.icon }}</span>
        <span :class="s.text">
          <strong :class="s.itemTitle">{{ item.title }}</strong>
          <span :class="s.itemDesc">{{ item.desc }}</span>
        </span>
      </a>
    </div>
    <template v-if="banner">
      <div :class="s.divider" />
      <a :href="banner.href" :class="s.banner">
        <span :class="s.bannerThumb">{{ banner.thumb }}</span>
        <span :class="s.bannerBody">
          <strong :class="s.bannerTitle">{{ banner.title }}</strong>
          <span :class="s.bannerDesc">{{ banner.desc }}</span>
        </span>
        <span :class="s.bannerArrow">→</span>
      </a>
    </template>
  </div>
</template>

<script setup>
import s from './NavDropdown.module.css';

defineProps({
  items:  { type: Array, default: () => [] },
  banner: { type: Object, default: null },
});
</script>

// src/components/layout/NavBar/NavDropdown.jsx
import styles from './NavDropdown.module.css';

/**
 * NavDropdown — Mega 下拉菜单
 * 结构：2列网格 × 4个菜单项 + 底部推广 Banner
 */
export default function NavDropdown({ items = [], banner }) {
  return (
    <div className={styles.dropdown}>
      {/* 菜单项网格 */}
      <div className={styles.grid}>
        {items.map((item) => (
          <a key={item.title} href={item.href} className={styles.item}>
            <span className={styles.icon}>{item.icon}</span>
            <span className={styles.text}>
              <strong className={styles.itemTitle}>{item.title}</strong>
              <span className={styles.itemDesc}>{item.desc}</span>
            </span>
          </a>
        ))}
      </div>

      {/* 底部推广 Banner */}
      {banner && (
        <>
          <div className={styles.divider} />
          <a href={banner.href} className={styles.banner}>
            <span className={styles.bannerThumb}>{banner.thumb}</span>
            <span className={styles.bannerBody}>
              <strong className={styles.bannerTitle}>{banner.title}</strong>
              <span className={styles.bannerDesc}>{banner.desc}</span>
            </span>
            <span className={styles.bannerArrow}>→</span>
          </a>
        </>
      )}
    </div>
  );
}
