// src/components/sections/TestimonialSection/TestimonialCard.jsx
import { useI18n } from '../../../i18n/index';
import styles from './TestimonialCard.module.css';

/**
 * TestimonialCard — 客户证言单张卡片
 */
export default function TestimonialCard({ industry, product, text, name, title, avatarGrad, avatarChar }) {
  return (
    <div className={styles.card}>
      {/* 标签行 */}
      <div className={styles.tags}>
        <span className={styles.tagIndustry}>{industry}</span>
        <span className={styles.tagProduct}>{product}</span>
      </div>

      {/* 引号 */}
      <div className={styles.quote} aria-hidden="true">"</div>

      {/* 正文 */}
      <p className={styles.text}>{text}</p>

      {/* 作者 */}
      <div className={styles.author}>
        <div
          className={styles.avatar}
          style={{ background: avatarGrad }}
          aria-hidden="true"
        >
          {avatarChar}
        </div>
        <div>
          <div className={styles.name}>{name}</div>
          <div className={styles.title}>{title}</div>
        </div>
      </div>
    </div>
  );
}

// src/components/sections/TestimonialSection/TestimonialCard.vue
<template>
  <div :class="s.card">
    <div :class="s.tags">
      <span :class="s.tagIndustry">{{ industry }}</span>
      <span :class="s.tagProduct">{{ product }}</span>
    </div>
    <div :class="s.quote" aria-hidden="true">"</div>
    <p :class="s.text">{{ text }}</p>
    <div :class="s.author">
      <div :class="s.avatar" :style="{ background: avatarGrad }" aria-hidden="true">
        {{ avatarChar }}
      </div>
      <div>
        <div :class="s.name">{{ name }}</div>
        <div :class="s.title">{{ title }}</div>
      </div>
    </div>
  </div>
</template>

<script setup>
import s from './TestimonialCard.module.css';

defineProps({
  industry:   { type: String, required: true },
  product:    { type: String, required: true },
  text:       { type: String, required: true },
  name:       { type: String, required: true },
  title:      { type: String, required: true },
  avatarGrad: { type: String, required: true },
  avatarChar: { type: String, required: true },
});
</script>
