// src/components/ui/DemoModal/ModalStep3.vue
<template>
  <div>
    <div :class="s.stepTitle">{{ t('modal.step3Title') }}</div>
    <div :class="s.stepSub">{{ t('modal.step3Sub') }}</div>
    <div :class="s.pills">
      <button
        v-for="scale in SCALES"
        :key="scale"
        :class="[s.pill, selected === scale ? s.pillSelected : '']"
        @click="selected = scale"
      >
        {{ scale }}
      </button>
    </div>
    <button :class="s.submitBtn" @click="emit('submit')">{{ t('modal.submit') }}</button>
  </div>
</template>

<script setup>
import { ref, inject } from 'vue';
import s from './DemoModal.module.css';

const { t } = inject('i18n', { t: (k) => k });
const SCALES = t('modal.scales') || [];
const selected = ref(SCALES[1] || '');

const emit = defineEmits(['submit']);
</script>

// src/components/ui/DemoModal/ModalStep3.jsx
import { useI18n } from '../../../i18n/index';
import { useState } from 'react';
import styles from './DemoModal.module.css';

/**
 * ModalStep3 — 企业规模（单选 Pills，默认第二项）
 */
export default function ModalStep3({ onSubmit }) {
  const { t } = useI18n();
  const SCALES = t('modal.scales') || [];
  const [selected, setSelected] = useState(SCALES[1] || '');

  return (
    <div>
      <div className={styles.stepTitle}>{t('modal.step3Title')}</div>
      <div className={styles.stepSub}>{t('modal.step3Sub')}</div>

      <div className={styles.pills}>
        {SCALES.map(s => (
          <button
            key={s}
            className={`${styles.pill} ${selected === s ? styles.pillSelected : ''}`}
            onClick={() => setSelected(s)}
          >
            {s}
          </button>
        ))}
      </div>

      <button className={styles.submitBtn} onClick={onSubmit}>
        {t('modal.submit')}
      </button>
    </div>
  );
}
