// src/components/ui/DemoModal/ModalSuccess.jsx
import { useI18n } from '../../../i18n/index';
import styles from './DemoModal.module.css';

/**
 * ModalSuccess — 提交成功态（2.5s 自动关闭）
 */
export default function ModalSuccess() {
  const { t } = useI18n();
  const lines = t('modal.successSub').split('\n');
  return (
    <div className={styles.success}>
      <div className={styles.successIcon}>🎉</div>
      <div className={styles.successTitle}>{t('modal.successTitle')}</div>
      <p className={styles.successSub}>
        {lines.map((line, i) => (
          <span key={i}>
            {line}
            {i < lines.length - 1 && <br />}
          </span>
        ))}
      </p>
    </div>
  );
}

// src/components/ui/DemoModal/ModalSuccess.vue
<template>
  <div :class="s.success">
    <div :class="s.successIcon">🎉</div>
    <div :class="s.successTitle">{{ t('modal.successTitle') }}</div>
    <p :class="s.successSub">
      <span v-for="(line, i) in lines" :key="i">
        {{ line }}
        <br v-if="i < lines.length - 1" />
      </span>
    </p>
  </div>
</template>

<script setup>
import { computed, inject } from 'vue';
import s from './DemoModal.module.css';

const { t } = inject('i18n', { t: (k) => k });
const lines = computed(() => t('modal.successSub').split('\n'));
</script>
