// src/components/ui/DemoModal/ModalStep2.vue
<template>
  <div>
    <div :class="s.stepTitle">{{ t('modal.step2Title') }}</div>
    <div :class="s.stepSub">{{ t('modal.step2Sub') }}</div>
    <div :class="s.pills">
      <button
        v-for="p in PRODUCTS"
        :key="p"
        :class="[s.pill, selected.has(p) ? s.pillSelected : '']"
        @click="toggle(p)"
      >
        {{ p }}
      </button>
    </div>
    <button :class="s.submitBtn" @click="emit('next')">{{ t('modal.next') }}</button>
  </div>
</template>

<script setup>
import { ref, inject, watch } from 'vue';
import s from './DemoModal.module.css';

const { t } = inject('i18n', { t: (k) => k });
const modalStore = inject('modal', { formData: { value: {} } });
const PRODUCTS = t('modal.products') || [];
const selected = ref(new Set(PRODUCTS.slice(0, 1)));

watch(selected, (val) => {
  modalStore.formData.value.products = Array.from(val);
}, { deep: true, immediate: true });

const toggle = (p) => {
  const next = new Set(selected.value);
  next.has(p) ? next.delete(p) : next.add(p);
  selected.value = next;
};

const emit = defineEmits(['next']);
</script>

// src/components/ui/DemoModal/ModalStep2.jsx
import { useI18n } from '../../../i18n/index';
import { useState } from 'react';
import styles from './DemoModal.module.css';

/**
 * ModalStep2 — 产品选择（多选 Pills，默认选中第一项）
 */
export default function ModalStep2({ onNext }) {
  const { t } = useI18n();
  const PRODUCTS = t('modal.products') || [];
  const [selected, setSelected] = useState(() => new Set(PRODUCTS.slice(0, 1)));

  const toggle = (p) => setSelected(prev => {
    const next = new Set(prev);
    next.has(p) ? next.delete(p) : next.add(p);
    return next;
  });

  return (
    <div>
      <div className={styles.stepTitle}>{t('modal.step2Title')}</div>
      <div className={styles.stepSub}>{t('modal.step2Sub')}</div>

      <div className={styles.pills}>
        {PRODUCTS.map(p => (
          <button
            key={p}
            className={`${styles.pill} ${selected.has(p) ? styles.pillSelected : ''}`}
            onClick={() => toggle(p)}
          >
            {p}
          </button>
        ))}
      </div>

      <button className={styles.submitBtn} onClick={onNext}>
        {t('modal.next')}
      </button>
    </div>
  );
}
