// src/components/ui/SectionHeader/SectionHeader.vue
<template>
  <div :class="[s.header, s[variant], className]">
    <Tag v-if="tag" :variant="tagVariant">{{ tag }}</Tag>
    <h2 :class="s.title">{{ title }}</h2>
    <p v-if="subtitle" :class="s.subtitle">{{ subtitle }}</p>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import Tag from '../Tag/Tag.vue';
import s from './SectionHeader.module.css';

const props = defineProps({
  tag:       { type: String, default: '' },
  title:     { type: String, required: true },
  subtitle:  { type: String, default: '' },
  variant:   { type: String, default: 'light' },
  className: { type: String, default: '' },
});

const tagVariant = computed(() => props.variant === 'dark' ? 'ai' : 'light');
</script>

// src/components/ui/SectionHeader/SectionHeader.jsx
import Tag from '../Tag/Tag';
import styles from './SectionHeader.module.css';

/**
 * SectionHeader — 通用区块标题组（Tag + H2 + Subtitle）
 * @param {'light'|'dark'} variant  - light=浅色区块, dark=深色区块
 */
export default function SectionHeader({
  tag,
  title,
  subtitle,
  variant   = 'light',
  className = '',
}) {
  const tagVariant = variant === 'dark' ? 'ai' : 'light';

  return (
    <div className={[styles.header, styles[variant], className].filter(Boolean).join(' ')}>
      {tag && <Tag variant={tagVariant}>{tag}</Tag>}
      <h2 className={styles.title}>{title}</h2>
      {subtitle && <p className={styles.subtitle}>{subtitle}</p>}
    </div>
  );
}
