// src/components/ui/Button/Button.vue
<template>
  <button
    :type="type"
    :class="[s.btn, s[variant], s[size], className]"
    @click="emit('click', $event)"
    :disabled="disabled"
  >
    <slot />
  </button>
</template>

<script setup lang="ts">
import s from './Button.module.css';

defineProps({
  variant:   { type: String, default: 'primary' },
  size:      { type: String, default: 'md' },
  className: { type: String, default: '' },
  type:      { type: String, default: 'button' },
  disabled:  { type: Boolean, default: false },
});
const emit = defineEmits(['click']);
</script>

// src/components/ui/Button/Button.jsx
import styles from './Button.module.css';

/**
 * Button — 全局按钮组件
 * @param {'primary'|'ghost'|'outline'|'white'} variant
 * @param {'md'|'sm'|'lg'} size
 */
export default function Button({
  children,
  variant   = 'primary',
  size      = 'md',
  onClick,
  className = '',
  type      = 'button',
  disabled  = false,
  ...rest
}) {
  const cls = [
    styles.btn,
    styles[variant],
    styles[size],
    className,
  ].filter(Boolean).join(' ');

  return (
    <button
      type={type}
      className={cls}
      onClick={onClick}
      disabled={disabled}
      {...rest}
    >
      {children}
    </button>
  );
}
