// src/components/sections/ProductMatrixSection/ProductCard.jsx
import styles from './ProductCard.module.css';

/**
 * ProductCard — 产品矩阵单张卡片
 * v2.1.0：icon 支持 SVG 组件（ReactElement）和 Emoji 字符串两种形式
 * iconColor: SVG currentColor 颜色
 * iconBg:    图标背景色
 */
export default function ProductCard({ icon: Icon, name, desc, iconBg, iconColor, linkText = "产品详情 →", delay = 0 }) {
  const delayClass = delay > 0 ? `reveal-delay-${delay}` : '';

  // 兼容：字符串 Emoji 直接渲染，函数组件调用渲染
  const iconContent = typeof Icon === 'function'
    ? <Icon />
    : Icon;

  return (
    <div className={`${styles.card} reveal ${delayClass}`}>
      <div
        className={styles.icon}
        style={{
          ...(iconBg    ? { background: iconBg }    : {}),
          ...(iconColor ? { color: iconColor }       : {}),
        }}
      >
        {iconContent}
      </div>
      <div className={styles.name}>{name}</div>
      <p  className={styles.desc}>{desc}</p>
      <span className={styles.link}>{linkText}</span>
    </div>
  );
}

// src/components/sections/ProductMatrixSection/ProductCard.vue
<template>
  <div :class="[s.card, 'reveal', delayClass]">
    <div :class="s.icon" :style="iconStyles">
      <component :is="icon" v-if="typeof icon === 'function'" />
      <template v-else>{{ icon }}</template>
    </div>
    <div :class="s.name">{{ name }}</div>
    <p :class="s.desc">{{ desc }}</p>
    <span :class="s.link">{{ linkText }}</span>
  </div>
</template>

<script setup>
import { computed } from 'vue';
import s from './ProductCard.module.css';

const props = defineProps({
  icon:      { type: [Function, String], required: true },
  name:      { type: String, required: true },
  desc:      { type: String, required: true },
  iconBg:    { type: String, default: '' },
  iconColor: { type: String, default: '' },
  linkText:  { type: String, default: '产品详情 →' },
  delay:     { type: Number, default: 0 },
});

const delayClass = computed(() => props.delay > 0 ? `reveal-delay-${props.delay}` : '');
const iconStyles = computed(() => ({
  ...(props.iconBg ? { background: props.iconBg } : {}),
  ...(props.iconColor ? { color: props.iconColor } : {}),
}));
</script>
