// src/pages/HomePage.vue
<template>
  <HeroSection />
  <Suspense>
    <template #fallback><SectionSkeleton :height="260" /></template>
    <BrandScrollSection />
  </Suspense>
  <Suspense>
    <template #fallback><SectionSkeleton :height="360" /></template>
    <StatsSection />
  </Suspense>
  <Suspense>
    <template #fallback><SectionSkeleton :height="720" /></template>
    <ProductMatrixSection />
  </Suspense>
  <Suspense>
    <template #fallback><SectionSkeleton :height="680" /></template>
    <AiFamilySection />
  </Suspense>
  <Suspense>
    <template #fallback><SectionSkeleton :height="640" /></template>
    <IndustrySolutionSection />
  </Suspense>
  <Suspense>
    <template #fallback><SectionSkeleton :height="520" /></template>
    <TestimonialSection />
  </Suspense>
  <Suspense>
    <template #fallback><SectionSkeleton :height="580" /></template>
    <LogoWallSection />
  </Suspense>
  <Suspense>
    <template #fallback><SectionSkeleton :height="760" /></template>
    <WhyUsSection />
  </Suspense>
  <Suspense>
    <template #fallback><SectionSkeleton :height="620" /></template>
    <ResourceSection />
  </Suspense>
  <Suspense>
    <template #fallback><SectionSkeleton :height="440" /></template>
    <CtaBannerSection />
  </Suspense>
</template>

<script setup>
import { defineAsyncComponent } from 'vue';
import HeroSection from '@/components/sections/HeroSection/HeroSection.vue';

const BrandScrollSection      = defineAsyncComponent(() => import('@/components/sections/BrandScrollSection/BrandScrollSection.vue'));
const StatsSection            = defineAsyncComponent(() => import('@/components/sections/StatsSection/StatsSection.vue'));
const ProductMatrixSection    = defineAsyncComponent(() => import('@/components/sections/ProductMatrixSection/ProductMatrixSection.vue'));
const AiFamilySection         = defineAsyncComponent(() => import('@/components/sections/AiFamilySection/AiFamilySection.vue'));
const IndustrySolutionSection = defineAsyncComponent(() => import('@/components/sections/IndustrySolutionSection/IndustrySolutionSection.vue'));
const TestimonialSection      = defineAsyncComponent(() => import('@/components/sections/TestimonialSection/TestimonialSection.vue'));
const LogoWallSection         = defineAsyncComponent(() => import('@/components/sections/LogoWallSection/LogoWallSection.vue'));
const WhyUsSection            = defineAsyncComponent(() => import('@/components/sections/WhyUsSection/WhyUsSection.vue'));
const ResourceSection         = defineAsyncComponent(() => import('@/components/sections/ResourceSection/ResourceSection.vue'));
const CtaBannerSection        = defineAsyncComponent(() => import('@/components/sections/CtaBannerSection/CtaBannerSection.vue'));
</script>

<script>
/* 骨架屏组件（不渲染任何内容，仅提供高度占位防 CLS） */
export default {
  components: {
    SectionSkeleton: {
      props: { height: { type: Number, default: 400 } },
      template: '<div :style="{ minHeight: height + \'px\' }" aria-hidden="true" />',
    },
  },
};
</script>

// src/pages/HomePage.jsx
import { lazy, Suspense } from 'react';
import HeroSection from '../components/sections/HeroSection/HeroSection';
import styles from './HomePage.module.css';

/* ── 首屏下方 Section 懒加载（降低 TTI）── */
const BrandScrollSection      = lazy(() => import('../components/sections/BrandScrollSection/BrandScrollSection'));
const StatsSection            = lazy(() => import('../components/sections/StatsSection/StatsSection'));
const ProductMatrixSection    = lazy(() => import('../components/sections/ProductMatrixSection/ProductMatrixSection'));
const AiFamilySection         = lazy(() => import('../components/sections/AiFamilySection/AiFamilySection'));
const IndustrySolutionSection = lazy(() => import('../components/sections/IndustrySolutionSection/IndustrySolutionSection'));
const TestimonialSection      = lazy(() => import('../components/sections/TestimonialSection/TestimonialSection'));
const LogoWallSection         = lazy(() => import('../components/sections/LogoWallSection/LogoWallSection'));
const WhyUsSection            = lazy(() => import('../components/sections/WhyUsSection/WhyUsSection'));
const ResourceSection         = lazy(() => import('../components/sections/ResourceSection/ResourceSection'));
const CtaBannerSection        = lazy(() => import('../components/sections/CtaBannerSection/CtaBannerSection'));

/**
 * HomePage — 首页页面容器（v2.3.4 Phase 4）
 *
 * 代码分割策略：
 *   - HeroSection 同步加载（LCP 关键路径）
 *   - 其余 Section 懒加载（进入视口前由 Suspense 兜底）
 */
export default function HomePage() {
  return (
    <>
      {/* ── SEC-02 ✅ Hero（首屏关键路径，同步加载）── */}
      <HeroSection />

      {/* ── 首屏下方 Section（独立懒加载 + 高度占位防 CLS）── */}
      <Suspense fallback={<SectionSkeleton h={260} />}>
        <BrandScrollSection />
      </Suspense>
      <Suspense fallback={<SectionSkeleton h={360} />}>
        <StatsSection />
      </Suspense>
      <Suspense fallback={<SectionSkeleton h={720} />}>
        <ProductMatrixSection />
      </Suspense>
      <Suspense fallback={<SectionSkeleton h={680} />}>
        <AiFamilySection />
      </Suspense>
      <Suspense fallback={<SectionSkeleton h={640} />}>
        <IndustrySolutionSection />
      </Suspense>
      <Suspense fallback={<SectionSkeleton h={520} />}>
        <TestimonialSection />
      </Suspense>
      <Suspense fallback={<SectionSkeleton h={580} />}>
        <LogoWallSection />
      </Suspense>
      <Suspense fallback={<SectionSkeleton h={760} />}>
        <WhyUsSection />
      </Suspense>
      <Suspense fallback={<SectionSkeleton h={620} />}>
        <ResourceSection />
      </Suspense>
      <Suspense fallback={<SectionSkeleton h={440} />}>
        <CtaBannerSection />
      </Suspense>
    </>
  );
}

/** 懒加载 Section 的轻量占位骨架（避免 layout shift）
 *  每个 Section 独立 Suspense，高度按真实内容估算，彻底消除 CLS */
function SectionSkeleton({ h = 400 }) {
  return <div className={styles.lazyPlaceholder} style={{ minHeight: h }} aria-hidden="true" />;
}
