// src/components/sections/IndustrySolutionSection/IndustrySolutionSection.vue
<template>
  <section :class="s.section" id="industry">
    <div class="container">
      <RevealWrapper>
        <SectionHeader
          :tag="t('industry.sectionTag')"
          :title="t('industry.sectionTitle')"
          :subtitle="t('industry.sectionSub')"
        />
      </RevealWrapper>
      <RevealWrapper>
        <TabNav
          :tabs="translatedTabs"
          :active-index="activeIndex"
          variant="pill"
          @select="selectTab"
        />
      </RevealWrapper>
      <div :class="s.panel">
        <div :class="s.features">
          <RevealWrapper v-for="(feat, i) in features" :key="feat.badge" :delay="i">
            <div :class="s.featureItem">
              <span :class="s.badge">{{ feat.badge }}</span>
              <div :class="s.featureBody">
                <strong>{{ feat.title }}</strong>
                <p>{{ feat.desc }}</p>
              </div>
            </div>
          </RevealWrapper>
          <RevealWrapper :delay="3">
            <button :class="s.cta" @click="modalStore.openModal()">{{ t('industry.getCta') }}</button>
          </RevealWrapper>
        </div>
        <RevealWrapper :delay="2" :class-name="s.screenshotWrap">
          <ProductScreenshot :screenshot="panel.screenshot" />
        </RevealWrapper>
      </div>
    </div>
  </section>
</template>

<script setup>
import { computed, inject, ref } from 'vue';
import { INDUSTRY_TABS } from '@/data/industries.js';
import { INDUSTRY_KEY_MAP } from '@/i18n/keyMap.js';
import { useTabs } from '@/composables/useTabs.js';
import { useApiData } from '@/composables/useApiData.js';
import { cmsApi } from '@/api/cms.js';
import { transformIndustries } from '@/api/transforms.js';
import SectionHeader from '../../ui/SectionHeader/SectionHeader.vue';
import TabNav from '../../ui/TabNav/TabNav.vue';
import ProductScreenshot from './ProductScreenshot.vue';
import RevealWrapper from '../../ui/RevealWrapper/RevealWrapper.vue';
import s from './IndustrySolutionSection.module.css';

const { t } = inject('i18n', { t: (k) => k });
const modalStore = inject('modal', { openModal: () => {} });
const { activeIndex, selectTab } = useTabs(0);

// API 数据（fallback 为静态数据）
const apiIndustries = ref([]);
useApiData(async () => {
  const data = await cmsApi.getIndustries();
  return transformIndustries(data);
}, apiIndustries);

const tabs = computed(() => (apiIndustries.value.length > 0 ? apiIndustries.value : INDUSTRY_TABS));

const panel = computed(() => tabs.value[activeIndex.value]);
const indKey = computed(() => INDUSTRY_KEY_MAP[panel.value.id] ?? panel.value.id);

const translatedTabs = computed(() => tabs.value.map(tab => ({
  ...tab,
  label: t(`industry.tabs.${INDUSTRY_KEY_MAP[tab.id] ?? tab.id}`),
})));

const features = computed(() => {
  // 优先使用 API 返回的 features（如果有）
  if (panel.value.features && panel.value.features.length > 0) {
    return panel.value.features;
  }
  // 回退到 i18n
  return [
    { badge: t('industry.badges.f1'), title: t(`industry.${indKey.value}.f1title`), desc: t(`industry.${indKey.value}.f1desc`) },
    { badge: t('industry.badges.f2'), title: t(`industry.${indKey.value}.f2title`), desc: t(`industry.${indKey.value}.f2desc`) },
    { badge: t('industry.badges.f3'), title: t(`industry.${indKey.value}.f3title`), desc: t(`industry.${indKey.value}.f3desc`) },
  ];
});
</script>

// src/components/sections/IndustrySolutionSection/IndustrySolutionSection.jsx
import { INDUSTRY_TABS }         from '../../../data/industries';
import { useTabs }               from '../../../hooks/useTabs';
import { useModalContext }       from '../../../context/ModalContext';
import { useI18n }               from '../../../i18n/index';
import { INDUSTRY_KEY_MAP }      from '../../../i18n/keyMap';
import SectionHeader             from '../../ui/SectionHeader/SectionHeader';
import TabNav                    from '../../ui/TabNav/TabNav';
import ProductScreenshot         from './ProductScreenshot';
import RevealWrapper             from '../../ui/RevealWrapper/RevealWrapper';
import styles                    from './IndustrySolutionSection.module.css';

export default function IndustrySolutionSection() {
  const { activeIndex, selectTab } = useTabs(0);
  const { openModal } = useModalContext();
  const { t }         = useI18n();
  const panel         = INDUSTRY_TABS[activeIndex];
  const indKey        = INDUSTRY_KEY_MAP[panel.id] ?? panel.id;

  // 用 i18n key 覆盖 tab label
  const translatedTabs = INDUSTRY_TABS.map(tab => ({
    ...tab,
    label: t(`industry.tabs.${INDUSTRY_KEY_MAP[tab.id] ?? tab.id}`),
  }));

  // 用 i18n 构建当前 panel 的 features（3 条）
  const features = [
    { badge: t('industry.badges.f1'), title: t(`industry.${indKey}.f1title`), desc: t(`industry.${indKey}.f1desc`) },
    { badge: t('industry.badges.f2'), title: t(`industry.${indKey}.f2title`), desc: t(`industry.${indKey}.f2desc`) },
    { badge: t('industry.badges.f3'), title: t(`industry.${indKey}.f3title`), desc: t(`industry.${indKey}.f3desc`) },
  ];

  return (
    <section className={`section ${styles.section}`} id="industry">
      <div className="container">
        <RevealWrapper>
          <SectionHeader
            tag={t('industry.sectionTag')}
            title={t('industry.sectionTitle')}
            subtitle={t('industry.sectionSub')}
          />
        </RevealWrapper>

        <RevealWrapper>
          <TabNav
            tabs={translatedTabs}
            activeIndex={activeIndex}
            onSelect={selectTab}
            variant="pill"
          />
        </RevealWrapper>

        <div className={styles.panel}>
          {/* 左侧：特色功能列表 */}
          <div className={styles.features}>
            {features.map((feat, i) => (
              <RevealWrapper key={feat.badge} delay={i}>
                <div className={styles.featureItem}>
                  <span className={styles.badge}>{feat.badge}</span>
                  <div className={styles.featureBody}>
                    <strong>{feat.title}</strong>
                    <p>{feat.desc}</p>
                  </div>
                </div>
              </RevealWrapper>
            ))}
            <RevealWrapper delay={3}>
              <button className={styles.cta} onClick={openModal}>
                {t('industry.getCta')}
              </button>
            </RevealWrapper>
          </div>

          {/* 右侧：产品截图卡 */}
          <RevealWrapper delay={2} className={styles.screenshotWrap}>
            <ProductScreenshot screenshot={panel.screenshot} indKey={indKey} />
          </RevealWrapper>
        </div>
      </div>
    </section>
  );
}
