// src/components/sections/StatsSection/StatsSection.vue
<template>
  <RevealWrapper>
    <div :class="s.section">
      <div class="container">
        <div :class="s.grid">
          <StatItem
            v-for="(item, i) in displayStats"
            :key="item.id"
            :target="item.target"
            :suffix="item.suffix"
            :label="t(`stats.${item.id}`)"
            :is-last="i === displayStats.length - 1"
          />
        </div>
      </div>
    </div>
  </RevealWrapper>
</template>

<script setup>
import { computed, inject, ref } from 'vue';
import { STATS_DATA } from '@/data/stats.js';
import { useApiData } from '@/composables/useApiData.js';
import { cmsApi } from '@/api/cms.js';
import { transformStats } from '@/api/transforms.js';
import RevealWrapper from '../../ui/RevealWrapper/RevealWrapper.vue';
import StatItem from './StatItem.vue';
import s from './StatsSection.module.css';

const { t } = inject('i18n', { t: (k) => k });

const apiStats = ref([]);
useApiData(async () => {
  const data = await cmsApi.getStats();
  return transformStats(data);
}, apiStats);

const displayStats = computed(() => (apiStats.value.length > 0 ? apiStats.value : STATS_DATA));
</script>

// src/components/sections/StatsSection/StatsSection.jsx
import { STATS_DATA } from '../../../data/stats';
import { useCountUp } from '../../../hooks/useCountUp';
import { useI18n }    from '../../../i18n/index';
import RevealWrapper  from '../../ui/RevealWrapper/RevealWrapper';
import styles         from './StatsSection.module.css';

export default function StatsSection() {
  const { t } = useI18n();
  return (
    <RevealWrapper>
      <div className={styles.section}>
        <div className="container">
          <div className={styles.grid}>
            {STATS_DATA.map((item, i) => (
              <StatItem
                key={item.id}
                target={item.target}
                suffix={item.suffix}
                label={t(`stats.${item.id}`)}
                isLast={i === STATS_DATA.length - 1}
              />
            ))}
          </div>
        </div>
      </div>
    </RevealWrapper>
  );
}

function StatItem({ target, suffix, label, isLast }) {
  const { ref } = useCountUp(target, { suffix });
  return (
    <div className={[styles.item, isLast ? styles.last : ''].join(' ')}>
      <div className={styles.num}>
        <span ref={ref}>0</span>
        {/* suffix 已由 useCountUp 写入 textContent，此处不再重复渲染 */}
      </div>
      <div className={styles.label}>{label}</div>
    </div>
  );
}
