// src/components/sections/BrandScrollSection/BrandScrollSection.jsx
import { BRAND_LOGOS } from '../../../data/stats';
import { useI18n }    from '../../../i18n/index';
import styles         from './BrandScrollSection.module.css';

/**
 * BrandScrollSection — SEC-03
 * 品牌 Logo 无限水平滚动（CSS Marquee），hover 暂停
 * v2.3.0：label 文字国际化
 */
export default function BrandScrollSection() {
  const { t } = useI18n();
  const logos = [...BRAND_LOGOS, ...BRAND_LOGOS];

  return (
    <div className={styles.section}>
      <p className={styles.label}>{t('marquee.label')}</p>
      <div className={styles.wrapper}>
        <div className={styles.track}>
          {logos.map((name, i) => (
            <span key={i} className={styles.logo}>{name}</span>
          ))}
        </div>
      </div>
    </div>
  );
}

// src/components/sections/BrandScrollSection/BrandScrollSection.vue
<template>
  <div :class="s.section">
    <p :class="s.label">{{ t('marquee.label') }}</p>
    <div :class="s.wrapper">
      <div :class="s.track">
        <span v-for="(name, i) in logos" :key="i" :class="s.logo">{{ name }}</span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { inject } from 'vue';
import { BRAND_LOGOS } from '@/data/stats';
import s from './BrandScrollSection.module.css';

const { t } = useI18n();
const logos = [...BRAND_LOGOS, ...BRAND_LOGOS];
</script>
