// src/components/ui/ContactModal/ContactModal.vue
<template>
  <BaseModal
    :is-open="isOpen"
    :aria-label="t('contact.ariaLabel')"
    :overlay-class-name="s.overlay"
    @close="emit('close')"
  >
    <div :class="s.card">
      <button :class="s.close" @click="emit('close')" :aria-label="t('modal.close')">
        <Icon name="close" :size="18" />
      </button>
      <div :class="s.header">
        <div :class="s.avatar">
          <Icon name="message-circle" :size="28" color="var(--primary)" />
        </div>
        <div>
          <div :class="s.title">{{ t('contact.title') }}</div>
          <div :class="s.subtitle">{{ t('contact.subtitle') }}</div>
        </div>
      </div>
      <div :class="s.divider" />
      <div :class="s.contactItem">
        <span :class="s.contactIcon"><Icon name="phone" :size="20" /></span>
        <div>
          <div :class="s.contactLabel">{{ t('contact.phoneLabel') }}</div>
          <a :class="s.contactValue" href="tel:4008888888">400-888-8888</a>
        </div>
      </div>
      <div :class="s.contactItem">
        <span :class="s.contactIcon"><Icon name="clock" :size="20" /></span>
        <div>
          <div :class="s.contactLabel">{{ t('contact.timeLabel') }}</div>
          <div :class="s.contactValue">{{ t('contact.timeValue') }}</div>
        </div>
      </div>
      <div :class="s.qrWrap">
        <div :class="s.qrBox">
          <svg width="80" height="80" viewBox="0 0 80 80" fill="none">
            <rect x="1" y="1" width="78" height="78" rx="6" stroke="var(--gray-200)" stroke-width="1.5"/>
            <rect x="10" y="10" width="22" height="22" rx="2" stroke="var(--primary)" stroke-width="1.5" fill="none"/>
            <rect x="14" y="14" width="14" height="14" rx="1" fill="var(--primary-light)"/>
            <rect x="48" y="10" width="22" height="22" rx="2" stroke="var(--primary)" stroke-width="1.5" fill="none"/>
            <rect x="52" y="14" width="14" height="14" rx="1" fill="var(--primary-light)"/>
            <rect x="10" y="48" width="22" height="22" rx="2" stroke="var(--primary)" stroke-width="1.5" fill="none"/>
            <rect x="14" y="52" width="14" height="14" rx="1" fill="var(--primary-light)"/>
            <circle cx="52" cy="52" r="10" fill="var(--primary-light)" stroke="var(--primary)" stroke-width="1"/>
            <text x="52" y="56" text-anchor="middle" font-size="10" font-weight="700" fill="var(--primary)">微</text>
          </svg>
          <div :class="s.qrLabel">{{ t('contact.qrWechat') }}</div>
        </div>
        <div :class="s.qrBox">
          <svg width="80" height="80" viewBox="0 0 80 80" fill="none">
            <rect x="1" y="1" width="78" height="78" rx="6" stroke="var(--gray-200)" stroke-width="1.5"/>
            <rect x="10" y="10" width="22" height="22" rx="2" stroke="var(--ai-purple)" stroke-width="1.5" fill="none"/>
            <rect x="14" y="14" width="14" height="14" rx="1" fill="var(--ai-purple-lighter)"/>
            <rect x="48" y="10" width="22" height="22" rx="2" stroke="var(--ai-purple)" stroke-width="1.5" fill="none"/>
            <rect x="52" y="14" width="14" height="14" rx="1" fill="var(--ai-purple-lighter)"/>
            <rect x="10" y="48" width="22" height="22" rx="2" stroke="var(--ai-purple)" stroke-width="1.5" fill="none"/>
            <rect x="14" y="52" width="14" height="14" rx="1" fill="var(--ai-purple-lighter)"/>
            <circle cx="52" cy="52" r="10" fill="#F3E8FF" stroke="var(--ai-purple)" stroke-width="1"/>
            <text x="52" y="56" text-anchor="middle" font-size="10" font-weight="700" fill="var(--ai-purple)">公</text>
          </svg>
          <div :class="s.qrLabel">{{ t('contact.qrOfficial') }}</div>
        </div>
      </div>
      <button :class="s.cta" @click="emit('close')">{{ t('contact.cta') }}</button>
    </div>
  </BaseModal>
</template>

<script setup>
import { inject } from 'vue';
import Icon from '../Icon/Icon.vue';
import BaseModal from '../BaseModal/BaseModal.vue';
import s from './ContactModal.module.css';

const { t } = inject('i18n', { t: (k) => k });

defineProps({
  isOpen: { type: Boolean, required: true },
});
const emit = defineEmits(['close']);
</script>

// src/components/ui/ContactModal/ContactModal.jsx
import { useI18n } from '../../../i18n/index';
import BaseModal from '../BaseModal/BaseModal';
import styles from './ContactModal.module.css';

/**
 * ContactModal — 在线咨询联系卡片弹窗（v2.3.2 Phase 2 国际化）
 * z-index: 2100（高于 DemoModal 2000）
 */
export default function ContactModal({ isOpen, onClose }) {
  const { t } = useI18n();

  return (
    <BaseModal
      isOpen={isOpen}
      onClose={onClose}
      ariaLabel={t('contact.ariaLabel')}
      overlayClassName={styles.overlay}
    >
      <div className={styles.card}>
        <button className={styles.close} onClick={onClose} aria-label={t('modal.close')}>✕</button>

        <div className={styles.header}>
          <div className={styles.avatar}>💬</div>
          <div>
            <div className={styles.title}>{t('contact.title')}</div>
            <div className={styles.subtitle}>{t('contact.subtitle')}</div>
          </div>
        </div>

        <div className={styles.divider} />

        {/* 电话 */}
        <div className={styles.contactItem}>
          <span className={styles.contactIcon}>📞</span>
          <div>
            <div className={styles.contactLabel}>{t('contact.phoneLabel')}</div>
            <a className={styles.contactValue} href="tel:4008888888">400-888-8888</a>
          </div>
        </div>

        {/* 工作时间 */}
        <div className={styles.contactItem}>
          <span className={styles.contactIcon}>🕘</span>
          <div>
            <div className={styles.contactLabel}>{t('contact.timeLabel')}</div>
            <div className={styles.contactValue}>{t('contact.timeValue')}</div>
          </div>
        </div>

        {/* 微信 QR */}
        <div className={styles.qrWrap}>
          <div className={styles.qrBox}>
            {/* QR 占位 */}
            <svg width="80" height="80" viewBox="0 0 80 80" fill="none">
              <rect x="1" y="1" width="78" height="78" rx="6"
                stroke="var(--gray-200)" strokeWidth="1.5"/>
              <rect x="10" y="10" width="22" height="22" rx="2"
                stroke="var(--primary)" strokeWidth="1.5" fill="none"/>
              <rect x="14" y="14" width="14" height="14" rx="1"
                fill="var(--primary-light)"/>
              <rect x="48" y="10" width="22" height="22" rx="2"
                stroke="var(--primary)" strokeWidth="1.5" fill="none"/>
              <rect x="52" y="14" width="14" height="14" rx="1"
                fill="var(--primary-light)"/>
              <rect x="10" y="48" width="22" height="22" rx="2"
                stroke="var(--primary)" strokeWidth="1.5" fill="none"/>
              <rect x="14" y="52" width="14" height="14" rx="1"
                fill="var(--primary-light)"/>
              <circle cx="52" cy="52" r="10"
                fill="var(--primary-light)" stroke="var(--primary)" strokeWidth="1"/>
              <text x="52" y="56" textAnchor="middle"
                fontSize="10" fontWeight="700" fill="var(--primary)">微</text>
            </svg>
            <div className={styles.qrLabel}>{t('contact.qrWechat')}</div>
          </div>
          <div className={styles.qrBox}>
            <svg width="80" height="80" viewBox="0 0 80 80" fill="none">
              <rect x="1" y="1" width="78" height="78" rx="6"
                stroke="var(--gray-200)" strokeWidth="1.5"/>
              <rect x="10" y="10" width="22" height="22" rx="2"
                stroke="var(--ai-purple)" strokeWidth="1.5" fill="none"/>
              <rect x="14" y="14" width="14" height="14" rx="1"
                fill="var(--ai-purple-lighter)"/>
              <rect x="48" y="10" width="22" height="22" rx="2"
                stroke="var(--ai-purple)" strokeWidth="1.5" fill="none"/>
              <rect x="52" y="14" width="14" height="14" rx="1"
                fill="var(--ai-purple-lighter)"/>
              <rect x="10" y="48" width="22" height="22" rx="2"
                stroke="var(--ai-purple)" strokeWidth="1.5" fill="none"/>
              <rect x="14" y="52" width="14" height="14" rx="1"
                fill="var(--ai-purple-lighter)"/>
              <circle cx="52" cy="52" r="10"
                fill="#F3E8FF" stroke="var(--ai-purple)" strokeWidth="1"/>
              <text x="52" y="56" textAnchor="middle"
                fontSize="10" fontWeight="700" fill="var(--ai-purple)">公</text>
            </svg>
            <div className={styles.qrLabel}>{t('contact.qrOfficial')}</div>
          </div>
        </div>

        <button className={styles.cta} onClick={onClose}>
          {t('contact.cta')}
        </button>
      </div>
    </BaseModal>
  );
}
