// src/components/sections/AiFamilySection/AiCard.jsx
import styles from './AiCard.module.css';

/**
 * AiCard — AI Family 专区玻璃态卡片
 * @param {boolean} hot - 是否显示 HOT 🔥 徽章
 */
export default function AiCard({ icon: Icon, name, tagline, hot = false, hotLabel = "HOT 🔥", linkText = "产品详情 →", delay = 0 }) {
  const delayClass = delay > 0 ? `reveal-delay-${delay}` : '';
  const iconContent = typeof Icon === 'function' ? <Icon /> : Icon;

  return (
    <div className={`${styles.card} reveal ${delayClass}`}>
      {hot && <span className={styles.badge}>{hotLabel}</span>}
      {/* AI 专区图标：紫色，稍大显示 */}
      <div className={styles.icon} style={{ color: 'var(--ai-purple-light)' }}>{iconContent}</div>
      <div className={styles.name}>{name}</div>
      <p  className={styles.tagline}>{tagline}</p>
      <span className={styles.link}>{linkText}</span>
    </div>
  );
}

// src/components/sections/AiFamilySection/AiCard.vue
<template>
  <div :class="[s.card, 'reveal', delayClass]">
    <span v-if="hot" :class="s.badge">{{ hotLabel }}</span>
    <div :class="s.icon" style="color: var(--ai-purple-light)">
      <component :is="icon" v-if="typeof icon === 'function'" />
      <template v-else>{{ icon }}</template>
    </div>
    <div :class="s.name">{{ name }}</div>
    <p :class="s.tagline">{{ tagline }}</p>
    <span :class="s.link">{{ linkText }}</span>
  </div>
</template>

<script setup>
import { computed } from 'vue';
import s from './AiCard.module.css';

const props = defineProps({
  icon:     { type: [Function, String], required: true },
  name:     { type: String, required: true },
  tagline:  { type: String, required: true },
  hot:      { type: Boolean, default: false },
  hotLabel: { type: String, default: 'HOT 🔥' },
  linkText: { type: String, default: '产品详情 →' },
  delay:    { type: Number, default: 0 },
});

const delayClass = computed(() => props.delay > 0 ? `reveal-delay-${props.delay}` : '');
</script>
