// src/components/sections/AiFamilySection/AiFamilySection.jsx
import { AI_CARDS, AI_BANNER }   from '../../../data/aiFamily';
import { useModalContext }       from '../../../context/ModalContext';
import { useI18n }               from '../../../i18n/index';
import { AI_CARD_KEY_MAP }       from '../../../i18n/keyMap';
import RevealWrapper             from '../../ui/RevealWrapper/RevealWrapper';
import AiCard                    from './AiCard';
import styles                    from './AiFamilySection.module.css';

export default function AiFamilySection() {
  const { openModal } = useModalContext();
  const { t }         = useI18n();

  return (
    <section className={styles.section} id="ai">
      <div className={styles.dots} aria-hidden="true" />
      <div className="container">
        <RevealWrapper className={styles.header}>
          <span className={styles.tag}>{t('aiFamily.sectionTag')}</span>
          <h2 className={styles.title}>{t('aiFamily.sectionTitle')}</h2>
          <p className={styles.subtitle}>{t('aiFamily.sectionSub')}</p>
        </RevealWrapper>

        <div className={styles.grid}>
          {AI_CARDS.map((card, i) => {
            const k = AI_CARD_KEY_MAP[card.id];
            return (
              <AiCard
                key={card.id}
                icon={card.icon}
                name={k ? t(`aiFamily.cards.${k}.name`)    : card.name}
                tagline={k ? t(`aiFamily.cards.${k}.tagline`) : card.tagline}
                linkText={t('aiFamily.linkText')}
                hot={card.hot}
                hotLabel={t('aiFamily.hotBadge')}
                delay={i}
              />
            );
          })}

          {/* Banner 卡 */}
          <RevealWrapper className={styles.bannerCard}>
            <div className={styles.bannerInner}>
              <div>
                <div className={styles.bannerLabel}>{t('aiFamily.banner.label')}</div>
                <div className={styles.bannerTitle}>{t('aiFamily.banner.title')}</div>
                <div className={styles.bannerSub}>{t('aiFamily.banner.sub')}</div>
              </div>
              <button className={styles.bannerCta} onClick={openModal}>
                {t('aiFamily.banner.cta')}
              </button>
            </div>
          </RevealWrapper>
        </div>
      </div>
    </section>
  );
}

// src/components/sections/AiFamilySection/AiFamilySection.vue
<template>
  <section :class="s.section" id="ai">
    <div :class="s.dots" aria-hidden="true" />
    <div class="container">
      <RevealWrapper :class-name="s.header">
        <span :class="s.tag">{{ t('aiFamily.sectionTag') }}</span>
        <h2 :class="s.title">{{ t('aiFamily.sectionTitle') }}</h2>
        <p :class="s.subtitle">{{ t('aiFamily.sectionSub') }}</p>
      </RevealWrapper>

      <div :class="s.grid">
        <AiCard
          v-for="(card, i) in AI_CARDS"
          :key="card.id"
          :icon="card.icon"
          :name="cardKey(card.id) ? t(`aiFamily.cards.${cardKey(card.id)}.name`) : card.name"
          :tagline="cardKey(card.id) ? t(`aiFamily.cards.${cardKey(card.id)}.tagline`) : card.tagline"
          :link-text="t('aiFamily.linkText')"
          :hot="card.hot"
          :hot-label="t('aiFamily.hotBadge')"
          :delay="i"
        />

        <!-- Banner 卡 -->
        <RevealWrapper :class-name="s.bannerCard">
          <div :class="s.bannerInner">
            <div>
              <div :class="s.bannerLabel">{{ t('aiFamily.banner.label') }}</div>
              <div :class="s.bannerTitle">{{ t('aiFamily.banner.title') }}</div>
              <div :class="s.bannerSub">{{ t('aiFamily.banner.sub') }}</div>
            </div>
            <button :class="s.bannerCta" @click="modalStore.openModal()">
              {{ t('aiFamily.banner.cta') }}
            </button>
          </div>
        </RevealWrapper>
      </div>
    </div>
  </section>
</template>

<script setup>
import { inject } from 'vue';
import { AI_CARDS } from '@/data/aiFamily.js';
import { AI_CARD_KEY_MAP } from '@/i18n/keyMap.js';
import RevealWrapper from '../../ui/RevealWrapper/RevealWrapper.vue';
import AiCard from './AiCard.vue';
import s from './AiFamilySection.module.css';

const { t } = inject('i18n', { t: (k) => k });
const modalStore = inject('modal', { openModal: () => {} });

const cardKey = (id) => AI_CARD_KEY_MAP[id];
</script>
