// src/components/sections/CtaBannerSection/CtaBannerSection.jsx
import { useModalContext } from '../../../context/ModalContext';
import { useI18n }         from '../../../i18n/index';
import RevealWrapper       from '../../ui/RevealWrapper/RevealWrapper';
import styles              from './CtaBannerSection.module.css';

export default function CtaBannerSection() {
  const { openModal } = useModalContext();
  const { t }         = useI18n();
  return (
    <section className={styles.section} id="cta">
      <div className={styles.glow} aria-hidden="true" />
      <div className="container">
        <RevealWrapper className={styles.content}>
          <h2 className={styles.title}>{t('cta.title')}</h2>
          <p  className={styles.subtitle}>{t('cta.sub')}</p>
          <div className={styles.btns}>
            <button className={styles.btnWhite}   onClick={openModal}>{t('cta.btn1')}</button>
            <button className={styles.btnOutline} onClick={openModal}>{t('cta.btn2')}</button>
          </div>
        </RevealWrapper>
      </div>
    </section>
  );
}

// src/components/sections/CtaBannerSection/CtaBannerSection.vue
<template>
  <section :class="s.section" id="cta">
    <div :class="s.glow" aria-hidden="true" />
    <div class="container">
      <RevealWrapper :class-name="s.content">
        <h2 :class="s.title">{{ t('cta.title') }}</h2>
        <p :class="s.subtitle">{{ t('cta.sub') }}</p>
        <div :class="s.btns">
          <button :class="s.btnWhite" @click="modalStore.openModal()">{{ t('cta.btn1') }}</button>
          <button :class="s.btnOutline" @click="modalStore.openModal()">{{ t('cta.btn2') }}</button>
        </div>
      </RevealWrapper>
    </div>
  </section>
</template>

<script setup>
import { inject } from 'vue';
import RevealWrapper from '../../ui/RevealWrapper/RevealWrapper.vue';
import s from './CtaBannerSection.module.css';

const { t } = inject('i18n', { t: (k) => k });
const modalStore = inject('modal', { openModal: () => {} });
</script>
