// src/components/sections/WhyUsSection/MetricCard.vue
<template>
  <div :class="[s.card, 'reveal', delayClass]">
    <div :class="s.num">{{ num }}</div>
    <div :class="s.label">{{ label }}</div>
    <p :class="s.desc">{{ desc }}</p>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import s from './MetricCard.module.css';

const props = defineProps({
  num:   { type: String, required: true },
  label: { type: String, required: true },
  desc:  { type: String, required: true },
  delay: { type: Number, default: 0 },
});

const delayClass = computed(() => props.delay > 0 ? `reveal-delay-${props.delay}` : '');
</script>

// src/components/sections/WhyUsSection/MetricCard.jsx
import styles from './MetricCard.module.css';

/**
 * MetricCard — 「为什么选我们」指标卡片（深色背景）
 */
export default function MetricCard({ num, label, desc, delay = 0 }) {
  const delayClass = delay > 0 ? `reveal-delay-${delay}` : '';

  return (
    <div className={`${styles.card} reveal ${delayClass}`}>
      <div className={styles.num}>{num}</div>
      <div className={styles.label}>{label}</div>
      <p  className={styles.desc}>{desc}</p>
    </div>
  );
}
